version: '3'

services:
  jormungandr-1:
    image: adalove/jormungandr:1.1-jormungandr0.8.5
    restart: always
    environment:
      - RUST_BACKTRACE=full
      - GENESIS_BLOCK_HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
      - NODE_CONFIG_PATH=/conf/node-config.yaml
    ports:
      - "3001:3001"
    volumes:
      - node-data-1:/data
      - ./node-config-1.yaml:/conf/node-config.yaml
  jormungandr-2:
    image: adalove/jormungandr:1.1-jormungandr0.8.5
    restart: always
    environment:
      - RUST_BACKTRACE=full
      - GENESIS_BLOCK_HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
      - NODE_CONFIG_PATH=/conf/node-config.yaml
    ports:
      - "3002:3002"
    volumes:
      - node-data-2:/data
      - ./node-config-2.yaml:/conf/node-config.yaml
  jormungandr-3:
    image: adalove/jormungandr:1.1-jormungandr0.8.5
    restart: always
    environment:
      - RUST_BACKTRACE=full
      - GENESIS_BLOCK_HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
      - NODE_CONFIG_PATH=/conf/node-config.yaml
    ports:
      - "3003:3003"
    volumes:
      - node-data-3:/data
      - ./node-config-3.yaml:/conf/node-config.yaml
  monitor:
    image: adalove/thor:0.1.0
    restart: always
    command: ["/conf/thor.yaml"]
    volumes:
      - ./thor.yaml:/conf/thor.yaml

volumes:
  node-data-1:
    external: true
  node-data-2:
    external: true
  node-data-3:
    external: true